- name: Install Apache Tomcat on Ubuntu
  hosts: tomcat
  become: yes
  vars:
    tom_url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.37/bin/apache-tomcat-8.5.37.tar.gz
    tomcat_user: tomcat
    tomcat_group: tomcat
    tomcat_install_dir: /usr/local/tomcat8

  tasks:
    - name: Install OpenJDK
      apt:
        name: openjdk-8-jdk
        state: present
        update_cache: yes

    - name: Create Tomcat group
      group:
        name: "{{ tomcat_group }}"
        state: present

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/nologin
        home: "{{ tomcat_install_dir }}"

    - name: Download Tomcat Tar Ball
      get_url:
        url: "{{ tom_url }}"
        dest: /tmp/tomcat-8.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/tomcat-8.tar.gz
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        creates: "{{ tomcat_install_dir }}/apache-tomcat-8.5.37"

    - name: Set ownership and permissions for Tomcat
      file:
        path: "{{ item }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        recurse: yes
      with_items:
        - "{{ tomcat_install_dir }}"
        - "{{ tomcat_install_dir }}/apache-tomcat-8.5.37"

    - name: Create Tomcat service file
      template:
        src: templates/tomcat.service
        dest: /etc/systemd/system/tomcat.service

    - name: Reload systemd config
      systemd:
        daemon_reload: yes

    - name: Enable and start Tomcat service
      service:
        name: tomcat
        state: started
        enabled: yes
